### ISSUE TITLE
No way to create an index pattern with ES 6.1.0 and Kibiter 6.1.0

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#116]
I am testing latest GrimoireLab pip packages and this simple `docker-compose.yml`file:
```
elasticsearch:
  image: bitergia/elasticsearch:6.1.0
  command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
  ports:
    - "9200:9200"
  environment:
    - ES_JAVA_OPTS=-Xms3g -Xmx3g

kibiter:
  image: bitergia/kibiter:6.1.0-newmenu
  links:
    - elasticsearch
  ports:
   - "5601:5601"
  environment:
    - PROJECT_NAME=jsmanrique
    - NODE_OPTIONS=--max-old-space-size=1200
    - ELASTICSEARCH_URL=http://elasticsearch:9200

mariadb:
  restart: on-failure:5
  image: mariadb:10.0
  ports:
    - "127.0.0.1:3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD= *******************************************
    - MYSQL_ALLOW_EMPTY_PASSWORD=********************************
  command: --wait_timeout=2592000 --interactive_timeout=2592000 --max_connections=300
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "3"
```

Sadly, each time I run a `mordred.cfg` file, I get a Kibiter without an index pattern configured and I am not able to set up one through Kibiter interface. The cause seems to be a wrong `.kibana` index has been created first.

The only way to achieve a running dashboard has been to remove existing `.kibana`
```
$ curl -X DELETE 'http://localhost:9200/.kibana'
```

Now, I can set up an index pattern and play with the data.

As collateral damage of removing the `.kibana` index, the Kibiter dashboards navigation menu is lost!

Wouldn't it be nice that `mordred` takes care of setting up a default index pattern or something similar to @jgbarah  solution in its [Dockerfile](https://github.com/chaoss/grimoirelab/blob/master/docker/Dockerfile-full):
```
curl -XPOST "http://127.0.0.1:5601/api/kibana/settings/indexPattern:placeholder" \
          -H 'Content-Type: application/json' -H 'kbn-version: '${KB_VERSION} \
          -H 'Accept: application/json' -d '{"value": "*"}' \
--silent --output /dev/null ; \
```
