### ISSUE TITLE
Error running grimoirelab cointainer

### ISSUE THREAD

**Issue by flaviobeck** [chaoss/grimoirelab#168]
Hello,

I am trying to run Grimoirelab as container, and now I have following error:

sudo docker logs grimoirelab

2018-12-06 00:42:59,617 - grimoire_elk.elk - ERROR - Error feeding ocean from github (https://github.com/kibana/): 404 Client Error: Not Found for url: https://api.github.com/repos/kibana//issues?sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&direction=asc&state=all

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/kibana//issues?sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&direction=asc&state=all
2018-12-06 00:43:00,661 - grimoire_elk.elk - ERROR - Error feeding ocean from github (https://github.com/elasticsearch/): 404 Client Error: Not Found for url: https://api.github.com/repos/elasticsearch//issues?sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&direction=asc&state=all

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/elasticsearch//issues?sort=updated&since=1970-01-01T00%3A00%3A00%2B00%3A00&per_page=100&direction=asc&state=all

NOTE:
there are double slashes in the URL
elasticsearch//issues

------------------
This is my docker-compose.yml

```
version: '3.2'
services:
  grimoirelab:
    image: grimoirelab/full
    container_name: grimoirelab
    ports:
      - 5601:5601
      - 9200:9200
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=America/Sao_Paulo
    volumes:
      - ./grimoirelab/credentials.cfg:/override.cfg
      - ./grimoirelab/projects.json:/projects.json
      - ./grimoirelab/logs:/logs
      - ./grimoirelab/es-data:/var/lib/elasticsearch

```
My projects.json:
```
{
    "Elastic": {
      "git": [
          "http://github.com/elastic/kibana/",
          "http://github.com/elastic/elasticsearch/",
          "http://github.com/elastic/logstash",
          "http://github.com/elastic/beats"
      ],
        "github": [
            "http://github.com/elastic/kibana/",
            "http://github.com/elastic/elasticsearch/",
            "http://github.com/elastic/logstash",
            "http://github.com/elastic/beats"
        ],
        "discourse": [
          "https://discuss.elastic.co"
        ]
    }
}
```
My project.cfg
```
[general]
#short_name = CHAOSS
short_name = flaviobeck

[sortinghat]
# Use organizations file
load_orgs = false
orgs_file = orgs.json

# Organization name for people not affiliated to any organization
unaffiliated_group = Unknown

# Ids known to be bots
bots_names = [Beloved Bot]

# How to autoprofile
#autoprofile = [CHAOSS:manual,git,github]
autoprofile = [flaviobeck:manual,git,github]
```
