### ISSUE TITLE
Add support for SOCKS5 proxy to docker images

### ISSUE THREAD

**Issue by marcofranssen** [chaoss/grimoirelab#334]
To be able to connect to company internal git repositories it would be great if Socks5 proxies would be supported.

Currently the docker image doesn't support Socks5 and errors with the message if a Socks5 proxy is configured via environment variables.

I have tried adding the capability by updating the entrypoint. However that doesn't resolve the issue yet. For testing purposes I'm running the Socks5 proxy on my host machine, which I can reach using `host.docker.internal` from my containers.

```bash
#!/usr/bin/env bash

set -e

if [ ! -z "$all_proxy" ] || [ ! -z "$http_proxy" ] || [ ! -z "$https_proxy" ] ; then
  temp_all=$all_proxy
  temp_http=$http_proxy
  temp_https=$https_proxy
  unset all_proxy
  unset http_proxy
  unset https_proxy
  pip3 install --user --upgrade pysocks
  all_proxy=$temp_all
  http_proxy=$temp_http
  https_proxy=$temp_https
fi

/usr/local/bin/sirmordred "$@"
```

```yml
  grimoirelab:
    image: "grimoirelab/installed:${GRIMOIRELAB_VERSION}"
    restart: on-failure
    environment:
      all_proxy: socks5://host.docker.internal
      http_proxy: socks5://host.docker.internal
      https_proxy: socks5://host.docker.internal
      no_proxy: es01,es02,kibiter,elasticsearch,mariadb,github.com
    entrypoint: [ "/grimoirelab-entrypoint.sh" ]
    command: [ "-c", "/infra.cfg", "/dashboard.cfg", "/project.cfg", "/override.cfg" ]
```

I have tried the same with e.g. the `curlimages/curl:7.70.0` image, which works as expected.

```bash
docker run --rm --env http_proxy=socks5://host.docker.internal:1080 --env https_proxy=socks5://host.docker.internal:1080  curlimages/curl:7.70.0 -L bitbucket.my.company.internal.org
```

If I try to run `wget` from the grimoirelab container on the same it also fails with the message Socks5 protocol isn't supported.

Would be great if someone could update the container with the required dependencies. Installing pysocks as I did above at least removes the error at a python level, but it still is unable to connect to the resources. Probably we need some os level dependency to make this work, maybe inspiration can be retrieved from the `curlimages/curl:7.70.0` image on why it works there.
