### ISSUE TITLE
Change login(s) for Kibana

### ISSUE THREAD

**Issue by connorlindsey** [chaoss/grimoirelab#345]
How can I edit the Search Guard login for the Kibana dashboard? I'm currently running `docker-compose-secured`. 

Also, is it possible to create multiple logins from a configuration file or something similar? 

![image](https://user-images.githubusercontent.com/12838032/86029690-b6e56d00-b9f0-11ea-9f59-2e99657e8fb8.png)

**Comment by valeriocos** [comment]
Hi @connorlindsey ,

> How can I edit the Search Guard login for the Kibana dashboard? I'm currently running docker-compose-secured.

You should modify the line: https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose-secured.yml#L43

It would be great if you could add a Q&A in the [how to section of mordred](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#how-to-) to include your question and solution.

> Also, is it possible to create multiple logins from a configuration file or something similar?

I'm not familiar with this part of the platform, I'll ask internally and get back to you tomorrow

**Comment by connorlindsey** [comment]
Thanks for the quick reply. To clarify, I mean how can I change the username and password? The linked line was to the "If you have forgotten your username or password" message.

**Comment by sduenas** [comment]
Not sure if this is what you are looking for:

https://github.com/chaoss/grimoirelab-kibiter#docker-env-variables-for-the-secured-version

**Comment by valeriocos** [comment]
Hi @connorlindsey , sorry for the misunderstanding, please follows the steps below (thanks @zhquan for the help):

- modify the elasticsearch section in the docker-compose

```
elasticsearch:
      image: bitergia/elasticsearch:6.8.6-secured
      command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
      ports:
        - 9200:9200
      environment:
        - ES_JAVA_OPTS=-Xms2g -Xmx2g
      volumes:
        - <your-path>/sgconfig:/elasticsearch/plugins/search-guard-6/sgconfig
```

- Execute the docker-compose once to mirror the content of the sgconfig directory to `<your-path>/sgconfig`

- Generate a hash with https://bcrypt-generator.com/ by writing the string to encrypt, which will be the hash of the password (e.g., `connor`)

- Modify the file `sgconfig/sg_internal_users.yml` by adding the new user as follows (note that you can copy/paste the admin section and change the name of the section and hash)

```
#password is: admin
admin:
  readonly: true
  hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
  roles:
    - admin
  ..

#password is: connor
connor:
  readonly: true
  hash: $2y$12$vabYJuIFm3kTRE2fLC5qIuHwCnenXXTXF3/S792hMjg7R1DltuMMm
  roles:
    - admin
``` 

- restart the docker container of elasticsearch

- access kibiter with the new credentials

Hope this helps, and please consider to contribute to the Q&A of mordred with your question and solution, thanks!
