### ISSUE TITLE
Template/Guidelines for deploying Grimorelabs

### ISSUE THREAD

**Issue by velmurugan-balasubramanian** [chaoss/grimoirelab#374]
Hi, 

I just wanted to know if there are any guidelines or templates for deploying Grimorelabs in production for AWS or other cloud providers?

Thanks in advance :)

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian, thanks for showing interest in GrimoireLab.

> I just wanted to know if there are any guidelines or templates for deploying Grimorelabs in production for AWS or other cloud providers?

We have guides on how to deploy GrimoireLab, you can check [Getting started](https://github.com/chaoss/grimoirelab#getting-started). 

I have another blog post written by @jsmanrique, [GrimoireLab to measure an organization’s private development](https://blog.bitergia.com/2020/06/25/grimoirelab-to-measure-organizations-private-development/). This might help you. :slightly_smiling_face:

**Comment by vchrombie** [comment]
Hi @velmurugan-balasubramanian 
I would like to ask if my comment helped you.

Do you have any updates or questions regarding it?

**Comment by velmurugan-balasubramanian** [comment]
Hey @vchrombie 

I am totally sorry, I was thinking I replied to your suggestion. 

It was of great help, although we tried to decouple the services and deploy it in AWS and was having some issues

We tried to use AWS [RDS](https://aws.amazon.com/rds/) for MariaDB and [AWS Elasticsearch service](https://aws.amazon.com/elasticsearch-service/) for Elasticsearch and kibana bundled with the AWS Elasticsearch service instead of kibiter

I referred to 
Running grimoirelab/installed in this link https://chaoss.github.io/grimoirelab-tutorial/sirmordred/container.html#running-grimoirelabinstalled and https://chaoss.github.io/grimoirelab-tutorial/basics/supporting.html for supporting systems

my files 

**setup.cfg**
```
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/bitergia/logs
aliases_file = /home/bitergia/conf/aliases.json

[projects]
projects_file = /home/bitergia/conf/projects.json

[es_collection]
url = https://myelasticsearchURL.us-east-1.es.amazonaws.com

[es_enrichment]
url = https://myelasticsearchURL.us-east-1.es.amazonaws.com
autorefresh = true

[sortinghat]
host =myRDS.us-east-1.rds.amazonaws.com
user = USER
password = PASSWORD
database = demo_sh
load_orgs = true
orgs_file = /home/bitergia/conf/organizations.json
autoprofile = [github, pipermail, git]
matching = [email]
sleep_for = 100
unaffiliated_group = Unknown
affiliate = true
strict_mapping = false
reset_on_load = false
identities_file = [/home/bitergia/conf/identities.yml]
identities_format = grimoirelab

[panels]
kibiter_time_from = now-5y
kibiter_default_index = git
kibiter_url = https://myelasticsearchURL.us-east-1.es.amazonaws.com/_plugin/kibana/
# kibiter_version = 6.1.4-1
# gitlab-issues = true
# gitlab-merges = true

[phases]
collection = true
identities = true
enrichment = true
panels = true

#[bugzillarest]
#raw_index = bugzillarest_demo_raw
#enriched_index = bugzillarest_demo_enriched
#no-archive = true

#[confluence]
#no-archive = true
#raw_index = confluence_demo_raw
#enriched_index = confluence_demo_enriched

[git]
raw_index = git_demo_raw
enriched_index = git_demo_enriched
latest-items = true
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]

[discourse]
raw_index = discourse_freshworks-raw
enriched_index = discourse_freshworks-enriched
no-archive = true

```

**docker-compose.yml**
```
version: '2.2'

services:
    mordred:
      restart: on-failure:5
      image: bitergia/mordred:latest
      volumes:
        - ../default-grimoirelab-settings/setup.cfg:/home/bitergia/conf/setup.cfg
        - ../default-grimoirelab-settings/aliases.json:/home/bitergia/conf/aliases.json
        - ../default-grimoirelab-settings/projects.json:/home/bitergia/conf/projects.json
        - ../default-grimoirelab-settings/organizations.json:/home/bitergia/conf/organizations.json
        - ../default-grimoirelab-settings/identities.yml:/home/bitergia/conf/identities.yml
        - /tmp/:/home/bitergia/logs
      mem_limit: 4g
```
After making these changes, I am running `docker-compose up -d` in the docker-compose to start mordred 

Could you please let me know, what I am doing is correct? or is there a better way to solve this problem
