### ISSUE TITLE
Need help on to update grimoire to the latest release

### ISSUE THREAD

**Issue by maltif** [chaoss/grimoirelab#567]
Hello Team,

We have grimoire tool up and running since Aug 5, 2022 and we haven't updated since then. Could you please guide us what is best approach to update grimoire to the latest release version without affecting the current state of grimoire(current dashboard and github metrics)

--
Altif

**Comment by sduenas** [comment]
Hi @maltif, what version are you using? We are preparing big changes for the next release (0.8.0), there's a new service you will have to run a migration of a database. Maybe you will like to wait until that's ready. However, if you want to use the latest stable version, we can help you with that.

**Comment by maltif** [comment]
Hello @sduenas,
Thank you for the response. Currently, we're running **GrimoireLab 0.4.0 - (2022-06-29)** version and would like to use latest stable version. I'd really appreciate your help on this :)

**Comment by maltif** [comment]
@sduenas Could you please help me to update grimoire to latest stable version?

**Comment by sduenas** [comment]
@maltif how do you use grimorielab? Do you use the docker image or you run it with a different method like pythong packages or from the source code?

**Comment by maltif** [comment]
@sduenas I'm running as docker-compose setup and it's running on EC2 instance. First we did clone the GrimoireLab repo as below:

```
git clone https://github.com/chaoss/grimoirelab
```

Then Go to `docker-compose` folder and run the following command:

```
cd grimoirelab/docker-compose
sudo docker-compose up -d
```

**Comment by zhquan** [comment]
Hi @maltif 

The latest stable version is `grimoirelab/grimoirelab:0.7.1`. Follow these steps:
1. On `docker-compose/docker-compose.yml` add this version and rename `bitergia` to `grimoire`
```
    mordred:
      restart: on-failure:5
      image: grimoirelab/grimoirelab:0.7.1
      volumes:
        - ../default-grimoirelab-settings/setup.cfg:/home/grimoire/conf/setup.cfg
        - ../default-grimoirelab-settings/projects.json:/home/grimoire/conf/projects.json
        - ../default-grimoirelab-settings/organizations.json:/home/grimoire/organizations.json
        - ../default-grimoirelab-settings/identities.yml:/home/grimoire/conf/identities.yml
        - /tmp/:/home/grimoire/logs
```
2. On `default-grimoirelab-settings/setup.cfg` rename `bitergia` to `grimoire` example at https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg
```
[general]
short_name = GrimoireLab
update = true
min_update_delay = 60
debug = false
logs_dir = /home/grimoire/logs
bulk_size = 1000
scroll_size = 1000
aliases_file = /home/grimoire/aliases.json

[projects]
projects_file = /home/grimoire/conf/projects.json
```
3. Run docker
```
cd docker-compose
sudo docker-compose up -d
```

I hope it helps you.
