### ISSUE TITLE
To add new column Author_email in the Git Top Authors visualization

### ISSUE THREAD

**Issue by maltif** [chaoss/grimoirelab#572]
Hello Team,

We've a visualization for Git Top Authors.Currently, the "Author" column displays the GitHub username, which is chosen by the user.

We have been managing the GitHub username and corresponding corporate email in the "user.yaml" file, which is stored in one of our GitHub repositories. I would like to have an additional column called "Author_email" to the "Git Top Authors" visualization. This will make it easier to identify the username based on their email, as shown in the attached image.

I am interested in hearing your thoughts and ideas on this matter. Are there any existing approaches or solutions that could be used to implement this feature? 

![image (1)](https://user-images.githubusercontent.com/100792545/215159853-ffe101f0-2b58-4adc-9768-07da3d1ad113.png)

Thank you!

**Comment by WhiteWolf47** [comment]
@maltif i would like to work on this issue! Can you link the repo in which "user.yaml" file is stored

**Comment by maltif** [comment]
Thank you @WhiteWolf47 for the response. 
It's a private repository under my org. However, I can share the sample data which is stored in "user.yaml" file as mentioned below:

```yaml
---
maltif: # maltif is the GitHub Author name(username)
  corp_id: maltif # maltif is ldap user-id
  email: mo.altif@corp.com # email is corp mail id which we want to add as additional column in Top Author visual.
gkxp:
  corp_id: gkowalski
  email: gab.kawl@corp.com

```
Hope this helps.

Please let me know if you need any additional information.
